### ISSUE TITLE
Update `test.yml` with new github actions

### ISSUE THREAD

**Issue by franckgaga** [JuliaControl/ControlSystems.jl#975]
I tagged you somewhere with the same comment, but I'm raising an issue here for posterity.

Might be worth it to update the `test.yml` file in `ControlSystem.jl`. See https://discourse.julialang.org/t/with-julia-actions-setup-julia-you-can-now-specify-lts-and-pre-named-versions/

The interesting parts would be to update to `julia-actions/setup-julia@v2`, `actions/checkout@v4` and `julia-actions/cache@v2`. The v2 of cache speeds up the testing but requires this addition in the yml file:

```yml
    runs-on: ${{ matrix.os }} # new part just after this line:
    permissions: # needed for julia-actions/cache delete old caches that it has created
      actions: write
      contents: read
```

With v2 of `setup-julia` you can execute the tests on:

```yml
      matrix:
        version:
          - 'lts' # long-term support release
          - '1'   # latest stable 1.x release
          - 'pre' # latest stable prerelease
          # - 'nightly' # commented since noisy + 'pre' allows testing upcoming versions
```

IMO it covers large enough to see major issues for Julia version incompatibilities.
